### ISSUE TITLE
OME Tiff Information: Do we want to keep it? Also H5 Writer defaults balloon file size, see last comment

### ISSUE THREAD

**Issue by jmdelahanty** [Tyelab/bruker_pipeline#9]
Bruker outputs OME.tiff files after the ripper has completed but only the first image that's written is the `OME.tif` master file.  This contains any additional channels that are recorded at the time. So if two channels were recorded at once, the OME.tifs that are generated will ONLY have the master-file generated for `Ch1` which contains all the data for any subsequent channels inside recorded during a session.

I'm asking questions in a gitter chatroom for zarr developers who have been helpful so far but I haven't heard back about a couple other new things yet.

I'm currently able to parse the `OME` xml properly but am still learning about the different image tag numbers that are used. There doesn't appear to be a clear explanation for what these different tags are or what other tag information is available in the OME-tiff master file. Here's what I've found out so far about the structure:

```
root: OME
     Image:
     - AcquisitionDate: Empty dictionary
     - Pixels: Dictionary of dimension order, physical pixel size in micrometers (I think...), number of channels, number of images per channel, dims of x/y/z, and bit depth of images.
            Channel: IDs of channels encoded as Channel:1:0 being channel 1, Channel:1:1 being channel 2
                - TiffData: Channel, number of images gathered before this point, number of planes, mystery IFD value
                        Filename: Bottom level of each channel ID tree, elements for all images that are generated
```

As of 12/13/21, a method for parsing an OME-tiff master file structured as this one that will preserve the metadata of tiffs for chunked HDF5/zarr files has not been found.

Good news is that it appears that Deryn's code in MATLAB using the `h5write` function does know how to create chunks of data from the many tiffs! It will take some additional testing to make sure it's doing what we expect, but MATLAB may have solved this issue for us thankfully. Another piece of good news is that we can likely run multiple copies MATLAB at once because it looks like each conversion to H5 only uses 1 CPU for a conversion (probably because it's I/O dependent).

Unfortunately, it looks like MATLAB's `h5write` doesn't seem to know how to keep the OME metadata. It doesn't seem like not having the metadata gets in the way of any processing or sharing and I'm currently unaware of `NWB` uses `OME` data/can store it somehow. I've opened a discussion [here](https://github.com/NeurodataWithoutBorders/helpdesk/discussions/13) to find out more.

However the tiffs are processed, each channel should have it's own chunked dataset with chunks of around 300MB which consists of about 600 images each. This will make it so processing can be done upon smaller chunks on machines without using so much memory for single planes/recordings and, especially important, make it easy to display data on people's desktops in the office. If one day multiple channels are to be recorded (I've seen up to 6 at once in some forum posts!) consistently and we do decide to keep the OME information for a given session we'll probably want to get that data out of the xml and build chunked datasets automatically.

I've also commented on a Suite2p issue [here](https://github.com/MouseLand/suite2p/issues/749) to see if the developers/users believe that having chunked datasets makes sense/would be helpful. Other people have told me that it makes sense to do so, but the user in this question is somehow recording over 1 million images in a recording which is just bonkers. I don't know how in the world they're processing that... Regardless, Carsen Stringer, the lead developer from Janelia, basically said that making stacks is annoying (which it certainly is turning out to be...) and so maybe doing this is unnecessary. Will update this upon hearing answers...

For now, here's what I propose be done in the near future:

- [x] Make sure chunking is not interfering with h5 file creation when using Deryn's code
- [ ] See how multi-channel datasets are interpreted when writing out h5 chunks
- [ ] Parse out OME-xml and create independent datasets with retained OME information for each channel
- [x] See if creating tiff stacks is required for creating appropriately sized chunks using `dask`
- [x] Pending above, write out tiffs to stacks in parallel for channels/planes/subjects
- [x] Benchmark creation of h5 files with Dask vs MATLAB
- [x] Benchmark creation of zarr single core
- [x] Benchmark creation of zarr multi-threaded
- [x] Benchmark creation of zarr multi-processed
